// @generated by tools/generate-cleanroom-nrom.py; do not edit by hand.
// Oracle: py65 commit 3138e1b337734a9b2ac1ea90ee7a453514436221; BSD-3-Clause; see NOTICE.
// Claims: architectural instruction boundaries only; bus order and reset unchecked.

const PROGRAM: &[u8] = &[
    0xd8, 0xa2, 0xfd, 0x9a, 0xa9, 0x12, 0x8d, 0x02, 0x00, 0xad, 0x02, 0x08, 0x18, 0x69, 0x34, 0x8d,
    0xff, 0x17, 0xad, 0xff, 0x07, 0x48, 0xa9, 0x00, 0x68, 0x20, 0x80, 0xc0, 0x8d, 0x00, 0x60, 0xad,
    0x00, 0x60, 0xa9, 0xa5, 0x8d, 0x00, 0x80, 0xad, 0x00, 0x80, 0x8d, 0x01, 0x60, 0xad, 0x01, 0x60,
    0xa0, 0x03, 0x88, 0xd0, 0xfd, 0xa9, 0x80, 0x8d, 0x00, 0x01, 0xa2, 0x01, 0xbd, 0xff, 0x00, 0x4c,
    0xfb, 0xc0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x49, 0xff, 0x38, 0x2a, 0x60, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xa9, 0x00, 0xf0, 0x01, 0xea,
    0xa9, 0x5a, 0xea,
];

#[derive(Clone, Copy, Debug)]
pub struct CleanroomCase {
    pub name: &'static str,
    prg_banks: u8,
    pub image_sha256: &'static str,
    pub trace_sha256: &'static str,
    pub rows: usize,
    pub transitions: usize,
    pub final_cycles: u64,
    pub trace: &'static str,
}

impl CleanroomCase {
    #[must_use]
    pub fn image(self) -> Vec<u8> {
        let prg_len = usize::from(self.prg_banks) * 16 * 1024;
        let mut image = vec![0; 16 + prg_len + 8 * 1024];
        image[0..4].copy_from_slice(b"NES\x1a");
        image[4] = self.prg_banks;
        image[5] = 1;
        image[8] = 1;
        let program_offset = if self.prg_banks == 1 {
            16
        } else {
            16 + 16 * 1024
        };
        image[program_offset..program_offset + PROGRAM.len()].copy_from_slice(PROGRAM);
        if self.prg_banks == 2 {
            image[16] = 0x5a;
        }
        let vector = 16 + prg_len - 4;
        image[vector..vector + 2].copy_from_slice(&[0x00, 0xc0]);
        image
    }
}

pub const PY65_COMMIT: &str = "3138e1b337734a9b2ac1ea90ee7a453514436221";
pub const PY65_CPU_SHA256: &str =
    "bdae2b7ef3e2a38519a007412280107f330c6fc6433738364578fe8338e57e7e";
pub const CASES: &[CleanroomCase] = &[
    CleanroomCase {
        name: "nrom128",
        prg_banks: 1,
        image_sha256: "5c2ec95f814a51cd220d6b2200371596e2e6c9b1cc159e90f6b2fa3401b4b9e3",
        trace_sha256: "4a42a862c561fb2a394760c547d40d2d31687abe3bb50edaf1bf0394a414df8e",
        rows: 41,
        transitions: 40,
        final_cycles: 128,
        trace: r#"C000 D8 CLD A:00 X:00 Y:00 P:24 SP:FD CYC:7
C001 A2 FD LDX A:00 X:00 Y:00 P:24 SP:FD CYC:9
C003 9A TXS A:00 X:FD Y:00 P:A4 SP:FD CYC:11
C004 A9 12 LDA A:00 X:FD Y:00 P:A4 SP:FD CYC:13
C006 8D 02 00 STA A:12 X:FD Y:00 P:24 SP:FD CYC:15
C009 AD 02 08 LDA A:12 X:FD Y:00 P:24 SP:FD CYC:19
C00C 18 CLC A:12 X:FD Y:00 P:24 SP:FD CYC:23
C00D 69 34 ADC A:12 X:FD Y:00 P:24 SP:FD CYC:25
C00F 8D FF 17 STA A:46 X:FD Y:00 P:24 SP:FD CYC:27
C012 AD FF 07 LDA A:46 X:FD Y:00 P:24 SP:FD CYC:31
C015 48 PHA A:46 X:FD Y:00 P:24 SP:FD CYC:35
C016 A9 00 LDA A:46 X:FD Y:00 P:24 SP:FC CYC:38
C018 68 PLA A:00 X:FD Y:00 P:26 SP:FC CYC:40
C019 20 80 C0 JSR A:46 X:FD Y:00 P:24 SP:FD CYC:44
C080 49 FF EOR A:46 X:FD Y:00 P:24 SP:FB CYC:50
C082 38 SEC A:B9 X:FD Y:00 P:A4 SP:FB CYC:52
C083 2A ROL A:B9 X:FD Y:00 P:A5 SP:FB CYC:54
C084 60 RTS A:73 X:FD Y:00 P:25 SP:FB CYC:56
C01C 8D 00 60 STA A:73 X:FD Y:00 P:25 SP:FD CYC:62
C01F AD 00 60 LDA A:73 X:FD Y:00 P:25 SP:FD CYC:66
C022 A9 A5 LDA A:73 X:FD Y:00 P:25 SP:FD CYC:70
C024 8D 00 80 STA A:A5 X:FD Y:00 P:A5 SP:FD CYC:72
C027 AD 00 80 LDA A:A5 X:FD Y:00 P:A5 SP:FD CYC:76
C02A 8D 01 60 STA A:D8 X:FD Y:00 P:A5 SP:FD CYC:80
C02D AD 01 60 LDA A:D8 X:FD Y:00 P:A5 SP:FD CYC:84
C030 A0 03 LDY A:D8 X:FD Y:00 P:A5 SP:FD CYC:88
C032 88 DEY A:D8 X:FD Y:03 P:25 SP:FD CYC:90
C033 D0 FD BNE A:D8 X:FD Y:02 P:25 SP:FD CYC:92
C032 88 DEY A:D8 X:FD Y:02 P:25 SP:FD CYC:95
C033 D0 FD BNE A:D8 X:FD Y:01 P:25 SP:FD CYC:97
C032 88 DEY A:D8 X:FD Y:01 P:25 SP:FD CYC:100
C033 D0 FD BNE A:D8 X:FD Y:00 P:27 SP:FD CYC:102
C035 A9 80 LDA A:D8 X:FD Y:00 P:27 SP:FD CYC:104
C037 8D 00 01 STA A:80 X:FD Y:00 P:A5 SP:FD CYC:106
C03A A2 01 LDX A:80 X:FD Y:00 P:A5 SP:FD CYC:110
C03C BD FF 00 LDA A:80 X:01 Y:00 P:25 SP:FD CYC:112
C03F 4C FB C0 JMP A:80 X:01 Y:00 P:A5 SP:FD CYC:117
C0FB A9 00 LDA A:80 X:01 Y:00 P:A5 SP:FD CYC:120
C0FD F0 01 BEQ A:00 X:01 Y:00 P:27 SP:FD CYC:122
C100 A9 5A LDA A:00 X:01 Y:00 P:27 SP:FD CYC:126
C102 EA NOP A:5A X:01 Y:00 P:25 SP:FD CYC:128"#,
    },
    CleanroomCase {
        name: "nrom256",
        prg_banks: 2,
        image_sha256: "2ad84794c15183a10184b533adc69ffb9b3b2baf91fdaa7f271c25501904ddd0",
        trace_sha256: "13ac7f450b1744ba469bf5ba49053b53380e43b778e92033ccceaa67833c2404",
        rows: 41,
        transitions: 40,
        final_cycles: 128,
        trace: r#"C000 D8 CLD A:00 X:00 Y:00 P:24 SP:FD CYC:7
C001 A2 FD LDX A:00 X:00 Y:00 P:24 SP:FD CYC:9
C003 9A TXS A:00 X:FD Y:00 P:A4 SP:FD CYC:11
C004 A9 12 LDA A:00 X:FD Y:00 P:A4 SP:FD CYC:13
C006 8D 02 00 STA A:12 X:FD Y:00 P:24 SP:FD CYC:15
C009 AD 02 08 LDA A:12 X:FD Y:00 P:24 SP:FD CYC:19
C00C 18 CLC A:12 X:FD Y:00 P:24 SP:FD CYC:23
C00D 69 34 ADC A:12 X:FD Y:00 P:24 SP:FD CYC:25
C00F 8D FF 17 STA A:46 X:FD Y:00 P:24 SP:FD CYC:27
C012 AD FF 07 LDA A:46 X:FD Y:00 P:24 SP:FD CYC:31
C015 48 PHA A:46 X:FD Y:00 P:24 SP:FD CYC:35
C016 A9 00 LDA A:46 X:FD Y:00 P:24 SP:FC CYC:38
C018 68 PLA A:00 X:FD Y:00 P:26 SP:FC CYC:40
C019 20 80 C0 JSR A:46 X:FD Y:00 P:24 SP:FD CYC:44
C080 49 FF EOR A:46 X:FD Y:00 P:24 SP:FB CYC:50
C082 38 SEC A:B9 X:FD Y:00 P:A4 SP:FB CYC:52
C083 2A ROL A:B9 X:FD Y:00 P:A5 SP:FB CYC:54
C084 60 RTS A:73 X:FD Y:00 P:25 SP:FB CYC:56
C01C 8D 00 60 STA A:73 X:FD Y:00 P:25 SP:FD CYC:62
C01F AD 00 60 LDA A:73 X:FD Y:00 P:25 SP:FD CYC:66
C022 A9 A5 LDA A:73 X:FD Y:00 P:25 SP:FD CYC:70
C024 8D 00 80 STA A:A5 X:FD Y:00 P:A5 SP:FD CYC:72
C027 AD 00 80 LDA A:A5 X:FD Y:00 P:A5 SP:FD CYC:76
C02A 8D 01 60 STA A:5A X:FD Y:00 P:25 SP:FD CYC:80
C02D AD 01 60 LDA A:5A X:FD Y:00 P:25 SP:FD CYC:84
C030 A0 03 LDY A:5A X:FD Y:00 P:25 SP:FD CYC:88
C032 88 DEY A:5A X:FD Y:03 P:25 SP:FD CYC:90
C033 D0 FD BNE A:5A X:FD Y:02 P:25 SP:FD CYC:92
C032 88 DEY A:5A X:FD Y:02 P:25 SP:FD CYC:95
C033 D0 FD BNE A:5A X:FD Y:01 P:25 SP:FD CYC:97
C032 88 DEY A:5A X:FD Y:01 P:25 SP:FD CYC:100
C033 D0 FD BNE A:5A X:FD Y:00 P:27 SP:FD CYC:102
C035 A9 80 LDA A:5A X:FD Y:00 P:27 SP:FD CYC:104
C037 8D 00 01 STA A:80 X:FD Y:00 P:A5 SP:FD CYC:106
C03A A2 01 LDX A:80 X:FD Y:00 P:A5 SP:FD CYC:110
C03C BD FF 00 LDA A:80 X:01 Y:00 P:25 SP:FD CYC:112
C03F 4C FB C0 JMP A:80 X:01 Y:00 P:A5 SP:FD CYC:117
C0FB A9 00 LDA A:80 X:01 Y:00 P:A5 SP:FD CYC:120
C0FD F0 01 BEQ A:00 X:01 Y:00 P:27 SP:FD CYC:122
C100 A9 5A LDA A:00 X:01 Y:00 P:27 SP:FD CYC:126
C102 EA NOP A:5A X:01 Y:00 P:25 SP:FD CYC:128"#,
    },
];
